---
default:
  image: registry.u-bordeaux.fr/tthor/alpine-git
  tags: ['docker']

stages:
  - build
  - rule2

before_script:
  # Fix that damn Git Unsafe Repository (cve-2022-24765)
  - git config --global --add safe.directory $CI_PROJECT_DIR
  # Retrieves any submodules
  - git submodule update --init --recursive
  # Fetch all branches from repository
  - git fetch --all


pre-rule1:
  stage: pre
  script:
    - chmod +x .gitlab/test_gitignore.sh
    - cd .gitlab
    - ./test_gitignore.sh

rule2-job:
  stage: rule2
  script:
    - cd .gitlab && ./check_ci.sh rebase
